-- Stages
CREATE OR REPLACE STAGE employee_pictures_stage
    DIRECTORY = (ENABLE = TRUE);

Create or replace STAGE HVAC_STAGE
DIRECTORY = (ENABLE = TRUE);




---Login

create or replace TABLE POTOMAC_HVAC.PUBLIC.PASSWORD_RESETS (
	RESETID VARCHAR(50) NOT NULL,
	EMPLOYEEID VARCHAR(50) NOT NULL,
	RESET_TOKEN VARCHAR(100) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	EXPIRES_AT TIMESTAMP_NTZ(9),
	USED BOOLEAN DEFAULT FALSE,
	primary key (RESETID)
);
create or replace TABLE POTOMAC_HVAC.PUBLIC.PERMISSIONS (
	PERMISSIONID VARCHAR(50) NOT NULL,
	TABNAME VARCHAR(50) NOT NULL,
	ACCESS_LEVEL VARCHAR(50) NOT NULL,
	ROLEID VARCHAR(50) NOT NULL,
	primary key (PERMISSIONID)
);




--ALLSERVICES
create or replace TABLE POTOMAC_HVAC.PUBLIC.ALLSERVICES (
	SERVICEID VARCHAR(50) NOT NULL,
	SERVICENAME VARCHAR(100) NOT NULL,
	primary key (SERVICEID)
);

--APPOINTMENTS
create or replace TABLE POTOMAC_HVAC.PUBLIC.APPOINTMENTS (
	APPOINTMENTID VARCHAR(50) NOT NULL,
	CUSTOMERID VARCHAR(50) NOT NULL,
	TECHNICIANID VARCHAR(50) NOT NULL,
	SCHEDULED_TIME TIMESTAMP_NTZ(9),
	SERVICE_TYPE VARCHAR(20),
	NOTES VARCHAR(1000),
	STA_TUS VARCHAR(20) DEFAULT 'scheduled',
	END_TIME TIMESTAMP_NTZ(9),
	TECHNICIAN_NOTES VARCHAR(2000),
	primary key (APPOINTMENTID)
);

--
create or replace TABLE POTOMAC_HVAC.PUBLIC.APPOINTMENT_VISITS (
	VISITID VARCHAR(50) NOT NULL,
	APPOINTMENTID VARCHAR(50) NOT NULL,
	EMPLOYEEID VARCHAR(50) NOT NULL,
	VISIT_NOTES VARCHAR(16777216),
	VISIT_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (VISITID)
);

create or replace TABLE POTOMAC_HVAC.PUBLIC.CONDENSER_SERVICES (
	CODE VARCHAR(10) NOT NULL,
	NAME VARCHAR(100),
	CATEGORY VARCHAR(50),
	ESTIMATED_DURATION_MIN NUMBER(38,0),
	PARTS_REQUIRED ARRAY,
	DIFFICULTY_LEVEL VARCHAR(20),
	primary key (CODE)
);




create or replace TABLE POTOMAC_HVAC.PUBLIC.CUSTOMERS (
	CUSTOMERID VARCHAR(50) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PHONE VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(100),
	ADDRESS VARCHAR(255) NOT NULL,
	UNIT VARCHAR(100),
	CITY VARCHAR(100),
	STATE VARCHAR(100),
	ZIPCODE VARCHAR(100),
	LATITUDE NUMBER(9,6),
	LONGITUDE NUMBER(9,6),
	HAS_LOCK_BOX VARCHAR(10) DEFAULT 'No',
	LOCK_BOX_CODE VARCHAR(100),
	HAS_SAFETY_ALARM VARCHAR(10) DEFAULT 'No',
	SAFETY_ALARM VARCHAR(100),
	HOW_HEARD VARCHAR(50),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	LAST_QUOTE_ID VARCHAR(50),
	LAST_QUOTE_DATE TIMESTAMP_NTZ(9),
	NOTE VARCHAR(16777216),
	ENTRANCE_NOTE VARCHAR(16777216),
	REQUEST VARCHAR(100),
	OUTDOOR_UNIT_MODEL VARCHAR(255),
	OUTDOOR_UNIT_SERIAL_NUMBER VARCHAR(100),
	INDOOR_UNIT_MODEL VARCHAR(255),
	INDOOR_UNIT_SERIAL_NUMBER VARCHAR(100),
	THERMOSTAT_TYPE VARCHAR(100),
	THERMOSTAT_AGE NUMBER(38,0),
	UNIT_LOCATION VARCHAR(50),
	ACCESSIBILITY_LEVEL VARCHAR(20),
	ACCESSIBILITY_NOTES VARCHAR(16777216),
	OTHER_NOTES VARCHAR(16777216),
	primary key (CUSTOMERID)
);

create or replace TABLE POTOMAC_HVAC.PUBLIC.CUSTOMER_DOCUMENTS (
	DOC_ID VARCHAR(50) NOT NULL,
	CUSTOMERID VARCHAR(50) NOT NULL,
	DOC_TYPE VARCHAR(10) NOT NULL,
	DESCRIPTION VARCHAR(255),
	DOC_DATA VARCHAR(16777216),
	UPLOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (DOC_ID),
	foreign key (CUSTOMERID) references POTOMAC_HVAC.PUBLIC.CUSTOMERS(CUSTOMERID)
);
---------------------------------------------
---------------------------------------------
---------------------------------------------
create or replace TABLE POTOMAC_HVAC.PUBLIC.EMPLOYEES (
	EMPLOYEEID VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	ENAME VARCHAR(100) NOT NULL,
	EPHONE VARCHAR(20),
	EMAIL VARCHAR(100),
	HOURLYRATE NUMBER(10,2),
	primary key (EMPLOYEEID)
);

create or replace TABLE POTOMAC_HVAC.PUBLIC.EMPLOYEE_BREAK_ENTRIES (
	BREAKID VARCHAR(50) NOT NULL,
	EMPLOYEEID VARCHAR(50) NOT NULL,
	BREAK_START TIMESTAMP_NTZ(9),
	BREAK_END TIMESTAMP_NTZ(9),
	ENTRY_DATE DATE,
	primary key (BREAKID),
	foreign key (EMPLOYEEID) references POTOMAC_HVAC.PUBLIC.EMPLOYEES(EMPLOYEEID)
);

create or replace TABLE POTOMAC_HVAC.PUBLIC.EMPLOYEE_EARNINGS (
	EARNINGID VARCHAR(50) NOT NULL,
	EMPLOYEEID VARCHAR(50) NOT NULL,
	AMOUNT NUMBER(10,2) NOT NULL,
	EARNING_DATE DATE NOT NULL,
	DESCRIPTION VARCHAR(16777216),
	primary key (EARNINGID),
	foreign key (EMPLOYEEID) references POTOMAC_HVAC.PUBLIC.EMPLOYEES(EMPLOYEEID)
);


create or replace TABLE POTOMAC_HVAC.PUBLIC.EXPERTISE (
	EXPERTISEID VARCHAR(50) NOT NULL,
	EXPERTISENAME VARCHAR(50) NOT NULL,
	unique (EXPERTISENAME),
	primary key (EXPERTISEID)
);
create or replace TABLE POTOMAC_HVAC.PUBLIC.EMPLOYEE_EXPERTISE (
	EMPLOYEEID VARCHAR(50) NOT NULL,
	EXPERTISEID VARCHAR(50) NOT NULL,
	primary key (EMPLOYEEID, EXPERTISEID),
	foreign key (EMPLOYEEID) references POTOMAC_HVAC.PUBLIC.EMPLOYEES(EMPLOYEEID),
	foreign key (EXPERTISEID) references POTOMAC_HVAC.PUBLIC.EXPERTISE(EXPERTISEID)
);


create or replace TABLE POTOMAC_HVAC.PUBLIC.EMPLOYEE_PICTURES (
	PICTUREID VARCHAR(50) NOT NULL,
	EMPLOYEEID VARCHAR(50) NOT NULL,
	PICTURE_DATA VARCHAR(16777216),
	UPLOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	PICTURE_DATA_TEXT VARCHAR(16777216),
	primary key (PICTUREID),
	foreign key (EMPLOYEEID) references POTOMAC_HVAC.PUBLIC.EMPLOYEES(EMPLOYEEID)
);

create or replace TABLE POTOMAC_HVAC.PUBLIC.ROLES (
	ROLEID VARCHAR(50) NOT NULL,
	ROLENAME VARCHAR(50) NOT NULL,
	unique (ROLENAME),
	primary key (ROLEID)
);


create or replace TABLE POTOMAC_HVAC.PUBLIC.EMPLOYEE_ROLES (
	EMPLOYEEID VARCHAR(50) NOT NULL,
    ENAME VARCHAR(100) NOT NULL,
	ROLEID VARCHAR(50) NOT NULL,
    
	primary key (EMPLOYEEID, ROLEID),
	foreign key (EMPLOYEEID) references POTOMAC_HVAC.PUBLIC.EMPLOYEES(EMPLOYEEID),
	foreign key (ROLEID) references POTOMAC_HVAC.PUBLIC.ROLES(ROLEID)
);

create or replace TABLE POTOMAC_HVAC.PUBLIC.EMPLOYEE_SCHEDULES (
	SCHEDULEID VARCHAR(50) NOT NULL,
	EMPLOYEEID VARCHAR(50) NOT NULL,
	SCHEDULE_DATE DATE NOT NULL,
	START_TIME TIME(9) NOT NULL,
	END_TIME TIME(9) NOT NULL,
	NOTES VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	unique (EMPLOYEEID, SCHEDULE_DATE),
	primary key (SCHEDULEID),
	foreign key (EMPLOYEEID) references POTOMAC_HVAC.PUBLIC.EMPLOYEES(EMPLOYEEID)
);

create or replace TABLE POTOMAC_HVAC.PUBLIC.EMPLOYEE_TIME_ENTRIES (
	ENTRYID VARCHAR(50) NOT NULL,
	EMPLOYEEID VARCHAR(50) NOT NULL,
	CLOCK_IN TIMESTAMP_NTZ(9),
	CLOCK_OUT TIMESTAMP_NTZ(9),
	ENTRY_DATE DATE,
	primary key (ENTRYID),
	foreign key (EMPLOYEEID) references POTOMAC_HVAC.PUBLIC.EMPLOYEES(EMPLOYEEID)
);


create or replace TABLE POTOMAC_HVAC.PUBLIC.TECHNICIAN_REPORTS (
	REPORTID VARCHAR(50) NOT NULL,
	CUSTOMERID VARCHAR(50) NOT NULL,
	TECHNICIANID VARCHAR(50) NOT NULL,
	TECHNICIAN_NAME VARCHAR(100) NOT NULL,
	REPORT_DATE DATE NOT NULL,
	SERVICE_TYPE VARCHAR(50) NOT NULL,
	HOURS_WORKED NUMBER(5,2) NOT NULL,
	PARTS_USED VARCHAR(16777216),
	WORK_PERFORMED VARCHAR(16777216) NOT NULL,
	RECOMMENDATIONS VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (REPORTID)
);

----------------------------------
----------------------------------
-----------------------------------
create or replace TABLE POTOMAC_HVAC.PUBLIC.EQUIPMENT (
	EQUIPMENTID VARCHAR(50) NOT NULL,
	EQUIPMENTNAME VARCHAR(100) NOT NULL,
	primary key (EQUIPMENTID)
);
create or replace TABLE POTOMAC_HVAC.PUBLIC.MATERIALS (
	MATERIALID VARCHAR(50) NOT NULL,
	MATERIALNAME VARCHAR(100) NOT NULL,
	primary key (MATERIALID)
);



----------------------------------
----------------------------------
-----------------------------------

create or replace file format condenser_services_file_format
   type = CSV,
   skip_header = 1,   
   field_delimiter = '%',
   trim_space = TRUE
;

SELECT $1, $2, $3, $4, $5
FROM @HVAC_STAGE/condenser_services_file
(FILE_FORMAT => condenser_services_file_format);

CREATE OR REPLACE TABLE condenser_services_table (
condenser_services_name VARCHAR(200) NOT NULL,
condenser_services_id VARCHAR(50) PRIMARY KEY
);

COPY INTO condenser_services_table
from @POTOMAC_HVAC.PUBLIC.HVAC_STAGE
files = ('condenser_services_file.txt')
file_format = (format_name = POTOMAC_HVAC.PUBLIC.condenser_services_file_format)
on_error = abort_statement
validation_mode = return_errors
purge = true;


create or replace TABLE POTOMAC_HVAC.PUBLIC.QUOTES (
	QUOTEID VARCHAR(50) NOT NULL,
	CUSTOMERID VARCHAR(50) NOT NULL,
	TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
	DESCRIPTION VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	QUOTE_NUMBER VARCHAR(20),
	STATUS VARCHAR(20) DEFAULT 'draft',
	SENT_DATE TIMESTAMP_NTZ(9),
	SENT_METHOD VARCHAR(20),
	primary key (QUOTEID)
);
create or replace TABLE POTOMAC_HVAC.PUBLIC.QUOTE_ITEMS (
	QUOTEID VARCHAR(50) NOT NULL,
	ITEM_TYPE VARCHAR(50) NOT NULL,
	ITEM_ID VARCHAR(50) NOT NULL,
	PRICE NUMBER(10,2) NOT NULL,
	QUANTITY NUMBER(38,0),
	foreign key (QUOTEID) references POTOMAC_HVAC.PUBLIC.QUOTES(QUOTEID)
);


--------------------------------------------
